server {
    listen 80;

}

server {
    listen 443 ssl;
    server_name dmitbud.tech www.dmitbud.tech;

    location / {
        proxy_pass http://localhost:8000;
    }

    location /static {
        root /var/dmitbud;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    ssl_certificate /etc/letsencrypt/live/dmitbud.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dmitbud.tech/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name dmitbud.tech www.dmitbud.tech;

    if ($host = www.dmitbud.tech) {
        return 301 https://$host$request_uri;
    }

    if ($host = dmitbud.tech) {
        return 301 https://$host$request_uri;
    }

    return 404;
}
